#!/usr/bin/env bash
#Program that prints FizzBuzz sequence
for num in {1..100}

do

  if (( num % 3 == 0 && num % 5 == 0 ))

  then

    echo "FizzBuzz"

  elif (( num % 3 == 0 ))

  then

    echo "Fizz"

  elif (( num % 5 == 0 ))

  then

    echo "Buzz"

  else

    echo "$num"

  fi
done
